### ISSUE TITLE
使用铅笔多画几次 就报错了

### ISSUE THREAD

**Issue by Blizzard-liu** [le5le-com/topology.js#25]
![image](https://user-images.githubusercontent.com/20244432/161173592-a19cd4bb-a8c4-4bc5-8def-1f05cbfb72d3.png)
url.7700b673.js:1 Uncaught TypeError: Cannot set properties of undefined (setting 'x')
    at zi.onMouseUp (url.7700b673.js:1:108784)
    at HTMLDivElement.mt.externalElements.onmouseup (url.7700b673.js:1:126949)
onMouseUp @ url.7700b673.js:1
mt.externalElements.onmouseup @ url.7700b673.js:1
25url.7700b673.js:1 Uncaught TypeError: Cannot set properties of undefined (setting 'x')
    at zi.onMouseUp (url.7700b673.js:1:108784)
    at zi.onMouseMove (url.7700b673.js:1:107653)
    at HTMLDivElement.mt.externalElements.onmousemove (url.7700b673.js:1:126797)

**Comment by ananzhusen** [comment]
@topology/core 1.1.35
