### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Blizzard-liu** [le5le-com/topology.js#40]
![ll](https://user-images.githubusercontent.com/20244432/163785317-fe4ff90a-5a52-4b80-8166-b0a68249de50.gif)
19url.0afeddfa.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'slice')
    at ft (url.0afeddfa.js:1:8648)
    at dt (url.0afeddfa.js:1:7443)
    at Xi.dirtyPenRect (url.0afeddfa.js:1:144366)
    at url.0afeddfa.js:1:148325
    at Array.forEach (<anonymous>)
    at Xi.resizePens (url.0afeddfa.js:1:147863)
    at Xi.onMouseMove (url.0afeddfa.js:1:104839)
    at HTMLDivElement.xt.externalElements.onmousemove (url.0afeddfa.js:1:125669)

**Comment by SignDawn** [comment]
修复过了，官网已经没有这个问题了。
如果使用的是 npm 包，等下个版本 1.1.5 ，如果不是，拉最新的核心库代码即可。
http://developer.le5le.com/topology-documents/tutorial/changelog.html
![image](https://user-images.githubusercontent.com/48878568/163796688-2c61cf9c-fe7e-4927-9a25-4f1dd8bbfbe3.png)
